### ISSUE TITLE
new website: www.kitura.dev but not kitura.dev

### ISSUE THREAD

**Issue by dannys42** [Kitura/kitura.io#452] opened 2020-10-02 19:03 UTC
Note, kitura.io is now www.kitura.dev.

Unfortunately kitura.dev is not working.  I've tried various ways of URL redirection, A ALIAS, and CNAME records, but none of those attempts seem to work.  URL redirection partially works, but only if the "http" is specified (not "https".  This is because of SSL cert issues.  I'm not sure exactly how to resolve this problem without having a dedicated web server running http + https doing a redirect to www.kitura.dev.

Anyone else have any thoughts?

**Comment by ddunn2** [comment] 2020-10-02 20:21
@dannys42 both URL's seem to work for me?

**Comment by futurejones** [comment] 2020-10-02 23:05
Make sure in in the advanced DNS settings on NameCheap you only have the following entries.
```
- A record for @ pointing to 185.199.108.153
- A record for @ pointing to 185.199.109.153
- A record for @ pointing to 185.199.110.153
- A record for @ pointing to 185.199.111.153
- CNAME record for www pointing to your username.github.io
```
All other records need to be removed.
Make sure you only have 1 CNAME record and no URL redirects
.dev domains are https only and will not work on http.

https://www.namecheap.com/support/knowledgebase/article.aspx/9645/2208/how-do-i-link-my-domain-to-github-pages

**Comment by dannys42** [comment] 2020-10-03 00:26
Thanks for the link!  A records were the first thing I tried, but they didn't work.  But I'll go through and follow the article and see if that helps.  

Also thanks for the tip about .dev domains and SSL.. I didn't even realize that was possible.  I wonder if it's the fact that it's a .dev domain that's causing problems.

**Comment by futurejones** [comment] 2020-10-03 00:35
I think it is the .dev causing the issues. 
From https://domains.google/tld/dev/

> We're making the web safer one .dev at a time. Every .dev domain is on the HSTS preload list, which makes HTTPS required on all connections. That means built-in security for you and your customers.

 Don't know what the answer is but there are a lot other sites with the same issue. I'll keep digging to see if I can find a cure.

**Comment by dannys42** [comment] 2020-10-03 00:50
*sigh* google...  Fortunately I did acquire kitura.net, so maybe that's the easier way to go.

**Comment by futurejones** [comment] 2020-10-03 00:54
@ddunn2 you said both urls are working for you, is there anything special about your setup or browser? I have tried numerous browsers on PC, Mac and mobile and none of them will load kitura.dev without the www.

**Comment by futurejones** [comment] 2020-10-03 01:11
In the repo site settings is the `Enforce HTTPS` option selected?

**Comment by futurejones** [comment] 2020-10-03 01:45
Try this.
1. make sure the DNS settings are 
```
- A record for @ pointing to 185.199.108.153
- A record for @ pointing to 185.199.109.153
- A record for @ pointing to 185.199.110.153
- A record for @ pointing to 185.199.111.153
- CNAME record for www pointing to your username.github.io
```
2. In the settings of the repo make sure the custom domain is `www.kitura.dev`
3. Make sure the `Enforce HTTPS` option is selected
4. Change the `CNAME` file in the master from `www.kitura.dev` to `kitura.dev`

**Comment by dannys42** [comment] 2020-10-03 03:54
Weird, I thought I had Enforce HTTPS enabled, but it is not.  I just tried enabling it.  I don't see any change yet, but I'll try again in the morning just in case there's any caching/propagation issues.

What's also weird is that kitura.io was registered through namecheap.  I tried to setup everything as similarly as possible... everywhere it says "www.kitura.io" I changed to "www.kitura.dev" and everywhere it just said "kitura.io" I changed to "kitura.dev".  So I'm not sure why it's not working.

If it continues to have issues I might try routing through Cloudflare and see if their URL will work.  (at least from their documentation, they say they will support URL redirection with https; whereas namecheap does not).

**Comment by futurejones** [comment] 2020-10-03 03:59
@dannys42 is the custom domain in the repo settings set to `www.kitura.dev` or `kitura.dev`?

**Comment by ddunn2** [comment] 2020-10-03 04:24
@futurejones it is `www.kitura.dev`

**Comment by futurejones** [comment] 2020-10-03 06:13
Ok, then all we need to do fix the problem is to change the setting to `kitura.dev`. This will generate the ssl certificate for `kitura.dev`. Check the site can be accessed on `kitura.dev` and then change it back to `www.kitura.dev`.
@ddunn2 do you have write access to the repo? If so can you try this.

**Comment by ddunn2** [comment] 2020-10-03 06:48
@futurejones I realised where you were going with this as soon as you asked whether it was set to `www.kitura.dev` or `kitura.dev` so I went ahead and changed it 😆 

It took a little while for the changes to propagate through, but I changed the custom domain to `kitura.dev` and enforced `https`, and now it seems to work for me on both `kitura.dev` and `www.kitura.dev` across browsers. 

I haven't changed the custom domain back to `www.kitura.dev` though. Do you think we still need to do this? 

Also if changing to `kitura.dev` is a solution we will need to update the CNAME

**Comment by futurejones** [comment] 2020-10-03 06:56
I am not sure, this is first time I have had this issue, its seems logical that the CNAME should be the same but in practice it may not matter. I think we will soon know if there is an issue once we start pushing through some more updates.

**Comment by mbarnach** [comment] 2020-10-03 07:11
Good job guys, now it works for both `www.kitura.dev` and `kitura.dev`!
I think we can close the issue.

**Comment by dannys42** [comment] 2020-10-03 16:48
@ddunn2 I guess that fixed it.  I don't quite understand since kitura.io I was configured as www.kitura.io and everything worked.  But as long as it all works now, I guess we're good!

**Comment by dannys42** [comment] 2020-10-03 16:48
Should I close this issue now?

**Closed** 2020-10-03 17:57 UTC
